#docker run -d --name samba -p 455:445 -e "USER=samba" -e "PASS=secret" -v "/home/storage:/storage" --restart=always dockurr/samba 

#docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest

#docker run --name mongo -p 27017:27017 -d mongo:latest

version: '3'
services:
    samba:
        image: dockurr/samba
        container_name: samba
        ports:
            - 455:445
        environment:
            - USER=samba
            - PASS=secret
        volumes:
            - /home/storage:/storage
        restart: always

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        ports:
            - 8000:8000
            - 9443:9443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        restart: always

    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - 27017:27017
        restart: always
    
    app:
      app:
    build: .
    ports:
      - "3000:3000"
    restart: always


volumes:
    portainer_data: